const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const api = (u,o={}) => fetch(u,{credentials:'include',headers:{'Content-Type':'application/json',...(o.headers||{})},...o}).then(async r=>{const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={success:false,error:t||r.statusText}};if(!r.ok&&!j.error)j.error=r.statusText;return j}).catch(e=>({success:false,error:e.message}));
const toast = t => { const el=$('#toast'); if(!el) return alert(t); el.textContent=t; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),3200); };
let session={local:null,twitch:null};
let currentRoom=null,currentTwitch=null,localStream=null,peers={},selectedGif='';
const socket = window.io ? io({withCredentials:true}) : null;
const navItems=[['home','Accueil','public'],['discover','Découvrir','public'],['watch','Live','public'],['twitch','Twitch','public'],['teams','Équipes','public'],['create','Ma chaîne','auth'],['dashboard','Dashboard','auth'],['moderation','Modération','auth'],['admin','Admin','admin'],['settings','Compte','public']];
function isAdminSession(){ return session.local?.login === 'sansahd' || !!session.local?.is_admin; }
function visibleNavItems(){return navItems.filter(([id,label,scope])=>scope==='public'||(scope==='auth'&&session.local)||(scope==='admin'&&isAdminSession()));}
function renderNav(){const items=visibleNavItems();$('#nav').innerHTML=items.map(([id,label])=>`<button data-v="${id}" onclick="setView('${id}')">${label}</button>`).join('');$('#bottomNav').innerHTML=items.filter(x=>['home','discover','watch','twitch','settings'].includes(x[0])).map(([id,label])=>`<button data-v="${id}" onclick="setView('${id}')">${label}</button>`).join('');highlightNav();}
function highlightNav(){const v=document.querySelector('.view.active')?.id||'home';$$('[data-v]').forEach(x=>x.classList.toggle('active',x.dataset.v===v));}
function setView(v){
  if(['create','dashboard','moderation'].includes(v)&&!session.local){toast('Compte Oryon requis.');v='settings';}
  if(v==='admin'&&!isAdminSession()){toast('Admin réservé à sansahd.');v='home';}
  $$('.view').forEach(x=>x.classList.toggle('active',x.id===v));
  history.replaceState(null,'','#'+v); highlightNav(); updateGates();
  if(v==='home') loadHome(); if(v==='discover') loadCategories(); if(v==='twitch') loadTwitchFollowed(); if(v==='dashboard') loadDashboard(); if(v==='teams') loadTeams(); if(v==='moderation') loadMod(); if(v==='admin') loadAdmin(); if(v==='settings') loadSettings();
}
function updateGates(){const logged=!!session.local;$$('.authOnly').forEach(x=>x.classList.toggle('hidden',!logged));$$('[data-authgate]').forEach(x=>x.classList.toggle('hidden',logged));$('#createContent')?.classList.toggle('hidden',!logged);$('#dashContent')?.classList.toggle('hidden',!logged);$('#modContent')?.classList.toggle('hidden',!logged);$('#teamGate')?.classList.toggle('hidden',logged);$('#twConnectBtn')?.classList.toggle('hidden',!!session.twitch);$('#twLogoutBtn')?.classList.toggle('hidden',!session.twitch);}
async function loadSession(){const s=await api('/api/oryon/session');session.local=s.local||null;session.twitch=s.twitch||null;$('#userLabel').textContent=session.local?.display_name||session.twitch?.display_name||'Connexion';$('#miniAvatar').style.backgroundImage=session.local?.avatar_url?`url(${session.local.avatar_url})`:'';renderUserMenu();renderNav();updateGates();await loadHome();loadFoundation();const h=location.hash.replace('#','');if(h&&document.getElementById(h))setView(h);}
function renderUserMenu(){const logged=!!session.local;$('#userDrop').innerHTML=`<div class="small">${logged?`Compte Oryon : <b>${esc(session.local.display_name)}</b>${isAdminSession()?' · Admin':''}`:'Non connecté Oryon'}</div><div class="sep"></div>${logged?`<button onclick="setView('create')">Ma chaîne</button><button onclick="setView('dashboard')">Dashboard</button><button onclick="setView('teams')">Équipes</button>${isAdminSession()?`<button onclick="setView('admin')">Admin</button>`:''}<button onclick="logoutOryon()">Déconnecter Oryon</button>`:`<button onclick="setView('settings')">Connexion / inscription</button>`}<div class="sep"></div>${session.twitch?`<div class="small">Twitch : <b>${esc(session.twitch.display_name)}</b></div><button onclick="setView('twitch')">Voir mes suivis Twitch</button><button onclick="disconnectTwitch()">Déconnecter Twitch</button>`:`<button onclick="connectTwitch()">Connecter Twitch</button>`}`;}
$('#userBtn').onclick=()=>$('#userDrop').classList.toggle('open');document.addEventListener('click',e=>{if(!e.target.closest('.userMenu'))$('#userDrop').classList.remove('open')});
function connectTwitch(){const w=560,h=760,left=(screen.width-w)/2,top=(screen.height-h)/2;const pop=window.open('/twitch_auth_start','twitch_auth',`width=${w},height=${h},left=${left},top=${top}`);if(!pop){location.href='/twitch_auth_start';return;}let tries=0;const timer=setInterval(async()=>{tries++;const st=await api('/twitch_user_status');if(st.is_connected){clearInterval(timer);try{pop.close()}catch{};toast('Twitch connecté');await loadSession();setView('twitch');}else if(tries>120||pop.closed){clearInterval(timer);await loadSession();}},1000);}
window.addEventListener('message',async e=>{if(e.data?.type==='ORYON_TWITCH_CONNECTED'){toast('Twitch connecté');await loadSession();setView('twitch');}});
async function disconnectTwitch(){await api('/twitch_logout',{method:'POST'});toast('Twitch déconnecté');session.twitch=null;await loadSession();}
async function logoutOryon(){await api('/api/oryon/logout',{method:'POST'});toast('Oryon déconnecté');session.local=null;await loadSession();setView('settings');}
function liveCard(x){const isTw=x.platform==='twitch'||!!x.login;const login=x.login||x.host_login||x.room;const title=x.title||`Live de ${login}`;const img=x.thumbnail_url||'';const viewers=x.viewer_count??x.viewers??0;return `<article class="liveCard"><div class="thumb">${img?`<img src="${esc(img)}" alt="">`:''}</div><div class="liveBody"><div class="title">${esc(title)}</div><div class="desc">${esc(x.game_name||x.category||'Oryon')} · ${viewers} viewers</div><div class="row section"><span class="pill">${isTw?'Twitch':'Oryon'}</span>${x.oryon_score?`<span class="pill">Score ${x.oryon_score}</span>`:''}</div><button class="btn section" onclick="${isTw?`openTwitch('${esc(login)}')`:`openOryon('${esc(login)}')`}">Regarder</button></div></article>`;}
async function loadHome(){const native=await api('/api/native/lives');const nitems=native.items||[];$('#nativeRail').innerHTML=nitems.length?nitems.map(liveCard).join(''):'<div class="empty">Aucun live natif actuellement. Oryon remonte donc des petits lives Twitch entre 10 et 50 viewers.</div>';const twUrl=nitems.length?'/api/twitch/streams/small?lang=fr&max=200':'/api/twitch/streams/small?lang=fr&min=10&max=50';const tw=await api(twUrl);$('#smallTwitchRail').innerHTML=(tw.items||[]).length?tw.items.map(liveCard).join(''):`<div class="empty">Aucun petit live Twitch trouvé. ${esc(tw.error||'')}</div>`;if(!$('#gemResult').dataset.loaded) await findGem();}
async function findGem(){const r=await api('/api/oryon/discover/find-live?lang=fr&max=200&mood=random');const items=(r.items||[]).slice(0,1);$('#gemResult').dataset.loaded='1';$('#gemResult').innerHTML=items.length?items.map(liveCard).join(''):'<div class="empty">Aucune pépite disponible maintenant. Essaie une catégorie.</div>';}
function presetFind(mood,max){$('#findMood').value=mood;$('#findMax').value=max;setView('discover');findLive();}
async function findLive(){const q=encodeURIComponent($('#findQ').value);const mood=$('#findMood').value;const max=$('#findMax').value;const lang=$('#findLang').value;const r=await api(`/api/oryon/discover/find-live?q=${q}&mood=${mood}&max=${max}&lang=${lang}`);$('#discoverResults').innerHTML=(r.items||[]).length?r.items.map(liveCard).join(''):'<div class="empty">Rien trouvé. Essaie moins restrictif.</div>';}
async function loadCategories(){const r=await api('/api/categories/top');let arr=(r.categories||r.items||r.data||[]).slice(0,48);if(!arr.length)arr=['Just Chatting','Minecraft','League of Legends','Grand Theft Auto V','Dungeons & Dragons','Art','Music','Fortnite','VALORANT','World of Warcraft'].map(name=>({name}));$('#categoriesGrid').innerHTML=arr.map(c=>{const name=c.name||c.game_name||c;const img=c.box_art_url||c.thumbnail_url||'';return `<button class="categoryCard" onclick="randomCategory('${esc(name)}')">${img?`<img src="${esc(img)}" alt="">`:''}<div class="catMeta"><b>${esc(name)}</b><span class="small">Live 0–200 viewers</span></div></button>`}).join('');}
async function randomCategory(name){const r=await api('/api/twitch/random-small-live?game='+encodeURIComponent(name)+'&max=200&language=fr');if(r.success&&r.target){openTwitch(r.target.login);toast('Petit live trouvé : '+r.target.name);}else toast(r.error||'Aucun petit live trouvé');}
async function loadTwitchFollowed(){if(!session.twitch){$('#followedRail').innerHTML='<div class="empty">Connecte Twitch pour afficher tes chaînes suivies en live.</div>';return;}let r=await api('/followed_streams');let items=(r.streams||[]).map(s=>({platform:'twitch',login:s.user_login,display_name:s.user_name,title:s.title,game_name:s.game_name,viewer_count:s.viewer_count,thumbnail_url:String(s.thumbnail_url||'').replace('{width}','640').replace('{height}','360')}));if(!items.length){r=await api('/api/twitch/followed/live');items=r.items||[]}$('#followedRail').innerHTML=items.length?items.map(liveCard).join(''):'<div class="empty">Aucune chaîne suivie en live maintenant.</div>';}
async function searchTwitch(){const q=$('#twSearch').value.trim();if(!q)return;const r=await api('/api/twitch/channels/search?q='+encodeURIComponent(q)+'&live=true');$('#twResults').innerHTML=(r.items||[]).map(x=>`<article class="liveCard"><div class="liveBody"><div class="row"><img class="avatarMini" src="${esc(x.profile_image_url||'')}" alt=""><b>${esc(x.display_name)}</b></div><p class="desc">${esc(x.title||x.game_name||'Chaîne Twitch')}</p><button class="btn" onclick="openTwitch('${esc(x.login)}')">Ouvrir</button></div></article>`).join('')||'<div class="empty">Aucun résultat.</div>';}
function openTwitch(login){currentTwitch=login;setView('twitch');const parent=location.hostname || 'localhost';$('#twitchPlayerTitle').textContent='Lecteur Twitch — '+login;$('#twitchPlayer').innerHTML=`<iframe allowfullscreen src="https://player.twitch.tv/?channel=${encodeURIComponent(login)}&parent=${encodeURIComponent(parent)}&muted=false"></iframe>`;$('#twitchChat').innerHTML=`<iframe src="https://www.twitch.tv/embed/${encodeURIComponent(login)}/chat?parent=${encodeURIComponent(parent)}&darkpopout"></iframe>`;}
async function openOryon(room){currentRoom=room;setView('watch');await loadChannelProfile(room);joinNative(room);}
async function loadChannelProfile(login){const r=await api('/api/oryon/profile/'+encodeURIComponent(login));const u=r.user||{};$('#channelName').textContent=u.display_name||login;$('#channelBio').textContent=u.bio||'Chaîne Oryon';$('#channelAvatar').src=u.avatar_url||'';$('#channelBanner').src=u.banner_url||'';$('#channelPills').innerHTML=(u.tags||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join('');}
function joinNative(room){currentRoom=room;socket?.emit('native:join',{room});$('#nativePlayer').innerHTML='<video id="remoteVideo" autoplay playsinline controls></video>';}
async function startNativeLive(payload){if(!session.local)return toast('Compte Oryon requis');currentRoom=session.local.login;let stream;try{stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});}catch{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});}localStream=stream;$('#nativePlayer').innerHTML='<video id="localVideo" autoplay muted playsinline controls></video>';$('#localVideo').srcObject=stream;setView('watch');await loadChannelProfile(session.local.login);socket?.emit('native:create',payload);toast('Live lancé. Il apparaît sur l’accueil.');}
function stopNativeLive(){socket?.emit('native:leave');if(localStream)localStream.getTracks().forEach(t=>t.stop());localStream=null;peers={};toast('Live arrêté');}
if(socket){socket.on('native:viewer',async d=>{if(!localStream)return;const pc=await makePeer(d.viewerId,true);localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('native:offer',{to:d.viewerId,room:currentRoom,offer});});socket.on('native:offer',async d=>{const pc=await makePeer(d.from,false);await pc.setRemoteDescription(d.offer);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);socket.emit('native:answer',{to:d.from,room:currentRoom,answer:ans});});socket.on('native:answer',async d=>{await peers[d.from]?.setRemoteDescription(d.answer);});socket.on('native:ice',d=>peers[d.from]?.addIceCandidate(d.candidate).catch(()=>{}));socket.on('native:error',e=>toast(e.message||'Erreur live'));socket.on('native:lives:update',loadHome);socket.on('native:chat',addChatMsg);socket.on('native:chat:history',d=>{$('#nativeChatLog').innerHTML=(d.messages||[]).map(renderMsg).join('');scrollChat();});}
async function makePeer(id){const cfg=await api('/api/webrtc/config');const pc=new RTCPeerConnection({iceServers:cfg.iceServers||[{urls:'stun:stun.l.google.com:19302'}]});peers[id]=pc;pc.onicecandidate=e=>{if(e.candidate)socket?.emit('native:ice',{to:id,room:currentRoom,candidate:e.candidate});};pc.ontrack=e=>{const v=$('#remoteVideo');if(v&&!v.srcObject)v.srcObject=e.streams[0];};return pc;}
function sendNativeChat(){if(!currentRoom)return toast('Aucun live sélectionné');socket?.emit('native:chat',{room:currentRoom,text:$('#chatInput').value,gif:selectedGif});$('#chatInput').value='';selectedGif='';$('#gifGrid').classList.add('hidden');}
function renderMsg(m){return `<div class="msg"><b>${esc(m.user_display||m.user)}</b> <span class="small">${new Date(m.ts).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</span><div>${esc(m.text||'')}</div>${m.gif?`<img src="${esc(m.gif)}" alt="gif">`:''}</div>`;}
function addChatMsg(m){$('#nativeChatLog').insertAdjacentHTML('beforeend',renderMsg(m));scrollChat();}
function scrollChat(){const l=$('#nativeChatLog');l.scrollTop=l.scrollHeight;}
async function toggleGifs(){const g=$('#gifGrid');g.classList.toggle('hidden');if(!g.classList.contains('hidden')){const r=await api('/api/gifs/search?q=funny');const gifs=(r.gifs||[]).slice(0,15);g.innerHTML=gifs.map(x=>`<img src="${esc(x.url||x.images?.fixed_height_small?.url||x)}" onclick="selectedGif=this.src;toast('GIF sélectionné')" alt="gif">`).join('')||'<div class="small">Aucun GIF.</div>';}}
function showChannelTab(tab){$$('.subTab').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase().includes(tab)));const data={about:'Bio, tags, règles du salon et score de proximité.',clips:'Clips courts et liens externes. VOD lourde évitée au MVP.',planning:'Planning public du créateur et prochains lives.',community:'Équipe, followers, raids inversés et salons.'};$('#channelTab').innerHTML=`<h3>${esc(tab)}</h3><p class="muted">${data[tab]||''}</p>`;}
async function followCurrent(){if(!session.local)return toast('Connecte-toi Oryon');if(!currentRoom)return toast('Aucune chaîne Oryon sélectionnée');const r=await api('/api/oryon/follow/'+currentRoom,{method:'POST'});toast(r.success?'Chaîne suivie':r.error||'Erreur');}
$('#goLiveForm').onsubmit=e=>{e.preventDefault();startNativeLive({title:$('#liveTitle').value,category:$('#liveCategory').value,tags:$('#liveTags').value});};
function fileToData(input,target){input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>target.value=r.result;r.readAsDataURL(f);};}
fileToData($('#avatarFile'),$('#profileAvatar'));fileToData($('#bannerFile'),$('#profileBanner'));
$('#profileForm').onsubmit=async e=>{e.preventDefault();const r=await api('/api/oryon/profile',{method:'POST',body:JSON.stringify({display_name:$('#profileDisplay').value,bio:$('#profileBio').value,avatar_url:$('#profileAvatar').value,banner_url:$('#profileBanner').value,tags:$('#profileTags').value})});toast(r.success?'Profil sauvegardé':r.error);await loadSession();};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const r=await api('/api/oryon/login',{method:'POST',body:JSON.stringify({login:$('#loginName').value,password:$('#loginPass').value})});toast(r.success?'Connecté':r.error);if(r.success){await loadSession();setView('create');}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();const r=await api('/api/oryon/register',{method:'POST',body:JSON.stringify({login:$('#regName').value,email:$('#regEmail').value,password:$('#regPass').value})});toast(r.success?'Compte créé':r.error);if(r.success){await loadSession();setView('create');}};
async function loadDashboard(){if(!session.local)return updateGates();const d=await api('/api/oryon/dashboard/full');const p=await api('/api/oryon/creator/progression');if(!d.success)return toast(d.error);const s=d.stats;$('#dashStats').innerHTML=[['Followers',s.followers],['Suivis',s.following],['Score',s.creator_score],['Live',s.live?'En direct':'Offline']].map(x=>`<div class="stat"><span class="small">${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#dashChart').innerHTML=(d.history||[]).map(h=>`<div class="bar" style="height:${Math.min(100,10+h.chat)}%"><span>${h.label}</span></div>`).join('');$('#levelBox').innerHTML=`<div class="stat"><span class="small">Niveau</span><b>${p.level||1}</b><p>${p.points||0} points futurs Trade</p><div class="progress"><i style="width:${Math.min(100,((p.points||0)/((p.nextLevelAt||100))) *100)}%"></i></div></div>`;$('#insights').innerHTML=(d.insights||[]).map(x=>`<p>• ${esc(x)}</p>`).join('');$('#bestSlots').innerHTML=(d.bestSlots||[]).map(x=>`<p><b>${esc(x.slot)}</b><br><span class="small">${esc(x.why)}</span></p>`).join('');$('#objectives').innerHTML=(p.objectives||[]).map(o=>`<div class="card"><b>${o.done?'✅':'⬜'} ${esc(o.label)}</b><p class="small">+${o.points} points</p></div>`).join('');$('#streamHistory').innerHTML=(d.streams||[]).map(x=>`<p><b>${esc(x.title)}</b> — pic ${x.peak}, chat ${x.chat}, follows ${x.follows}</p>`).join('');}
async function claimPoints(){const r=await api('/api/oryon/creator/progression/claim',{method:'POST'});toast(r.success?`+${r.gained} points`:r.error);loadDashboard();}
$('#planningForm').onsubmit=async e=>{e.preventDefault();const r=await api('/api/oryon/planning',{method:'POST',body:JSON.stringify({title:$('#planTitle').value,category:$('#planCategory').value,when:$('#planWhen').value})});toast(r.success?'Live planifié':r.error);loadPlanning();};
async function loadPlanning(){const r=await api('/api/oryon/planning?login='+(session.local?.login||''));$('#planningList').innerHTML=(r.items||[]).map(x=>`<div class="card"><b>${esc(x.title)}</b><p>${new Date(x.when).toLocaleString('fr-FR')}</p><span class="pill">${esc(x.category)}</span></div>`).join('')||'<div class="empty">Aucun live planifié.</div>';}
async function loadTeams(){const r=await api('/api/oryon/teams');$('#teamsList').innerHTML=(r.items||[]).map(t=>`<div class="card"><h3>${esc(t.name)}</h3><p class="muted">${esc(t.description)}</p><p>${t.members.length} membres · ${t.points} points</p><div class="row"><button class="btn" onclick="joinTeam('${esc(t.slug)}')">Rejoindre</button><button class="btn secondary" onclick="openTeam('${esc(t.slug)}')">Voir</button></div></div>`).join('')||'<div class="empty">Aucune équipe.</div>';}
$('#teamForm').onsubmit=async e=>{e.preventDefault();if(!session.local){toast('Connecte-toi à Oryon avant de créer une équipe.');setView('settings');return;}const r=await api('/api/oryon/teams',{method:'POST',body:JSON.stringify({name:$('#teamName').value,description:$('#teamDesc').value,tags:$('#teamTags').value})});toast(r.success?'Équipe créée':r.error);loadTeams();};
async function joinTeam(slug){if(!session.local){toast('Connecte-toi à Oryon avant de rejoindre une équipe.');setView('settings');return;}const r=await api('/api/oryon/teams/'+slug+'/join',{method:'POST'});toast(r.success?'Équipe rejointe':r.error);loadTeams();}
async function openTeam(slug){const r=await api('/api/oryon/teams/'+slug);if(!r.success)return toast(r.error);$('#teamsList').insertAdjacentHTML('afterbegin',`<div class="card"><h3>${esc(r.team.name)}</h3><p>${esc(r.team.description)}</p><p class="small">Membres live : ${(r.live_members||[]).length}</p></div>`);}
async function loadMod(){if(!session.local)return updateGates();const r=await api('/api/oryon/moderation/'+session.local.login);$('#modState').textContent=r.success?JSON.stringify(r.state,null,2):r.error;}
async function modAction(action){if(!session.local)return;const body={action,target:$('#modTarget').value,blocked_words:$('#blockedWords').value};const r=await api('/api/oryon/moderation/'+session.local.login,{method:'POST',body:JSON.stringify(body)});toast(r.success?'Modération mise à jour':r.error);loadMod();}
async function loadAdmin(){const r=await api('/api/oryon/admin/summary');if(!r.success){$('#adminBox').innerHTML=esc(r.error||'Admin indisponible');return;}$('#adminBox').innerHTML=`<div class="stats">${Object.entries(r.stats).map(([k,v])=>`<div class="stat"><span class="small">${k}</span><b>${v}</b></div>`).join('')}</div><h3 class="section">Signalements</h3>${(r.reports||[]).map(x=>`<p>${esc(x.user)} → ${esc(x.target||x.room)} : ${esc(x.reason)}</p>`).join('')||'<p class="muted">Aucun signalement.</p>'}`;}
async function loadFoundation(){const r=await api('/api/oryon/foundation/status');$('#foundationStatus').innerHTML=r.success?`Mode persistance : <b>${esc(r.persistence.mode)}</b><br>${esc(r.persistence.note)}<br>Admin : compte <b>sansahd</b>`:'Indisponible';}
async function loadSettings(){loadFoundation();$('#authPanel').classList.toggle('hidden',!!session.local);if(session.local){$('#profileDisplay').value=session.local.display_name||'';$('#profileBio').value=session.local.bio||'';$('#profileAvatar').value=session.local.avatar_url||'';$('#profileBanner').value=session.local.banner_url||'';}$('#connectionState').innerHTML=`<div class="statusLine"><span class="pill">Oryon : ${session.local?'connecté':'non connecté'}</span><span class="pill">Twitch : ${session.twitch?'connecté':'non connecté'}</span>${session.local?`<button class="btn secondary" onclick="logoutOryon()">Déconnecter Oryon</button>`:''}</div>`;if(session.local) loadPlanning();}
renderNav();loadSession();setInterval(()=>{if(document.querySelector('#home.active'))loadHome();},30000);
